apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-cgys
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-cbtg-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-cgys@sha256:9810df911877e5baa5b4bc4739cb11e736ee57a16b1398b5787bbf748d2cf696
        name: my-python
        resources: {}
status: {}
